### ISSUE TITLE
bug where pressing 't' would focus when chat not shown

### ISSUE THREAD

**Issue by yuszafar** [Stuyk/rebar-chat#5]
I updated to the latest version but when I press t the chat still doesn't open. I tried adding:
```
const chat = await api.getAsync('chat-api');
chat.show(player);
```
Chat started to open but messages do not appear in chat history after sending

**Comment by exhertz** [comment]
I think I've found the reason why the messages are being ignored.

The `src/main/server/systems/messenger.ts` contains function the `processMessage`
She checks for the presence of a character on the account, and you, like me, work on a bare account without creating a character.

```js
function processMessage(player: alt.Player, msg: string) {
    if (!player.valid) {
        return;
    }
    
    /* ↓ this */
    if (!useStatus(player).hasCharacter()) {
        return;
    }

    const messageSystem = useMessenger();
    if (msg.charAt(0) !== '/') {
        msg = cleanMessage(msg);
        alt.emit('rebar:playerSendMessage', player, msg);
        return;
    }

    const args = msg.split(' ');
    const commandName = args.shift();
    messageSystem.commands.invoke(player, commandName, ...args);
}
```

**Comment by yuszafar** [comment]
@exhertz Thank you
